// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcGM2H8i5UBdsPTi4o6RHlb9HnIhEgsWE',
    appId: '1:649053804470:web:2386cd8253dda16cca9317',
    messagingSenderId: '649053804470',
    projectId: 'brew-crew-bc72c',
    authDomain: 'brew-crew-bc72c.firebaseapp.com',
    storageBucket: 'brew-crew-bc72c.firebasestorage.app',
    measurementId: 'G-P977DLEEQM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRLPJOOqrIZGcZBgCs98pi1IgS-G9ktgY',
    appId: '1:649053804470:android:2816582382abca05ca9317',
    messagingSenderId: '649053804470',
    projectId: 'brew-crew-bc72c',
    storageBucket: 'brew-crew-bc72c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPK4pa_1_hlltB3LZctz20s6UP0uhCtMA',
    appId: '1:649053804470:ios:e34389a33ab52b2eca9317',
    messagingSenderId: '649053804470',
    projectId: 'brew-crew-bc72c',
    storageBucket: 'brew-crew-bc72c.firebasestorage.app',
    iosBundleId: 'com.example.brewCrew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPK4pa_1_hlltB3LZctz20s6UP0uhCtMA',
    appId: '1:649053804470:ios:e34389a33ab52b2eca9317',
    messagingSenderId: '649053804470',
    projectId: 'brew-crew-bc72c',
    storageBucket: 'brew-crew-bc72c.firebasestorage.app',
    iosBundleId: 'com.example.brewCrew',
  );
}
